// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package server

type NewTodo struct {
	Text     string `json:"text"`
	UserID   string `json:"userId"`
	UserName string `json:"userName"`
}
